# It builds the project on multiple operating systems (Ubuntu, Windows, and macOS)

name: Build Project

on:
  pull_request:
    branches:
      - main

jobs:
  debug:
    name: Debug Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        build-configuration: [ Debug, Release ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          args: -DCMAKE_BUILD_TYPE=${{ matrix.build-configuration }}