# This workflow is from https://github.com/official-stockfish/Stockfish/blob/master/.github/workflows/clang-format.yml#L23

# This workflow will run clang-format and comment on the PR.
# Because of security reasons, it is crucial that this workflow
# executes no shell script nor runs make.
# Read this before editing: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

name: ClangFormat check
on:
  pull_request_target:
    branches:
      - "main"
    paths:
      - "**.cpp"
      - "**.h"

# needed for automatic comment in pr
permissions:
  pull-requests: write

jobs:
  Clang-Format:
    name: Clang-Format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.15.0
        id: clang-format
        with:
          clang-format-version: "20"